### ISSUE TITLE
Create list of videos ID's and Video Names into text file

### ISSUE THREAD

**Issue by dynamitemedia** [jordoncm/youtube-dl-playlist#12]
i am just looking to get the youtube URL and name of video.

where would i change that info here?  and have it make a file like this?
say i grab this playlist:
https://www.youtube.com/playlist?list=PL2284887FAE36E6D8&feature=plcp

i just want them written to a text file like this:

1  https://www.youtube.com/watch?v=QGvvJO5UIs4   Learn Bash Scripts - Tutorial
2  https://www.youtube.com/watch?v=CsBVaJelurE   BASH lesson 2
3 ..
4...  ETC

**Comment by oskarrough** [comment]
You can do that quite easily with the YouTube API.

Because of their API limits you have to call this recursively, adjusting the index along the way until there are no more items.

`https://gdata.youtube.com/feeds/api/playlists/PL2284887FAE36E6D8?alt=jsonc&v=2&start-index=1&max-results=50`

All your videos will be in `data.items[]` where you'll also find the title and video id. Let me know if I can help.

**Comment by jordoncm** [comment]
If you take the fetchInfo method here and dump it into your own python script, it should help you just grad the playlist metadata and then you should be able to parse that result and find the titles.

https://github.com/jordoncm/youtube-dl-playlist/blob/master/youtube-dl-playlist#L69
